export const SEARCH_VIDEO = 'SEARCH_VIDEO';
export const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS';
export const SEARCH_VIDEO_FAILED = 'SEARCH_VIDEO_FAILED';

export const SELECT_VIDEO = 'SELECT_VIDEO';
export const SELECT_VIDEO_SUCCESS = 'SELECT_VIDEO_SUCCESS';
export const SELECT_VIDEO_FAILED = 'SELECT_VIDEO_FAILED';